name: Deploy to github pages
on:
    push:
        branches:
            - master
jobs:
    gh-pages-deploy:
        name: Deploying to gh-pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Clean install dependencies
              run: npm ci

            - name: Run deploy script
              run: |
                  git config user.name "ryeolkwang" && git config user.email "ryeolkwang@gmail.com"
                  npm run gh-pages-deploy
